---
- name: Oracle Database 19c Installation
  hosts: db_ora_install
  become: yes
  vars_files:
    - "/etc/ansible/playbooks/oracle_19c_install/vars.yml"

  pre_tasks:
    - name: Check Linux distribution
      fail:
        msg: "This playbook supports only RedHat Release 7, 8 family systems, but server os family is {{ ansible_facts['os_family'] }} Release {{ ansible_facts['distribution_major_version'] }}"
      when: ansible_facts['os_family'] != 'RedHat' or ansible_facts['distribution_major_version'] | int < 7

  roles:
    - role: db_storage_setup
      when: is_storage_setup_required|bool

    - role: db_server_setup
      when: is_server_setup_required|bool

    - role: db_software_setup
      when: is_database_software_setup_required|bool

    - role: db_create_instance
      when: is_database_creation_required|bool

    - role: db_crontab_scripts
      when: is_database_crontab_scripts_required|bool

    - role: cc_agent_setup
      when: is_cloud_control_agent_setup_required|bool
