---
# tasks file for db_crontab_scripts

- name: Create directories for scripts
  become: yes
  become_user: "{{ os_db_owner }}"
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    group: oinstall
    mode: '0775'
  with_items:
    - "/home/{{ os_db_owner }}/dba/scripts"
    - "/home/{{ os_db_owner }}/dba/logs/rman"
    - "{{ rman_bkp_location }}/{{ ora_db_sid }}"

- name: Copy scripts to target server
  become: yes
  become_user: "{{ os_db_owner }}"
  template:
    src: "{{ item.name }}"
    dest: "{{ item.location }}"
    mode: '0775'
  with_items:
    - { name: "ora_cleanup_diag.j2", location: "/home/{{ os_db_owner }}/dba/scripts/ora_cleanup_diag.sh" }
    - { name: "rman_backup.j2",      location: "/home/{{ os_db_owner }}/dba/scripts/rman_backup.sh" }

- name: Schedule scripts in {{ os_db_owner }} user crontab
  become: yes
  become_user: "{{ os_db_owner }}"
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    weekday: "{{ item.weekday }}"
    job: "{{ item.job }}"
    state: present
  with_items:
    - { name: "Remove Oracle Database Diagnostic files",
        minute: "05",
        hour: "00",
        weekday: "*",
        job: "/home/{{ os_db_owner }}/dba/scripts/ora_cleanup_diag.sh {{ oracle_base }} 1" }
    - { name: "RMAN - Hourly Archive Logs backup",
        minute: "05",
        hour: "*",
        weekday: "*",
        job: "/home/{{ os_db_owner }}/dba/scripts/rman_backup.sh {{ oracle_home }} {{ ora_db_sid }} arch 2 high {{ rman_bkp_location }}/{{ ora_db_sid }}" }
    - { name: "RMAN - Daily Level 1 Differential backup",
        minute: "30",
        hour: "0",
        weekday: "1-6",
        job: "/home/{{ os_db_owner }}/dba/scripts/rman_backup.sh {{ oracle_home }} {{ ora_db_sid }} lvl1_dif 2 high {{ rman_bkp_location }}/{{ ora_db_sid }}" }
    - { name: "RMAN - Weekly Sunday Level 0 backup",
        minute: "30",
        hour: "0",
        weekday: "0",
        job: "/home/{{ os_db_owner }}/dba/scripts/rman_backup.sh {{ oracle_home }} {{ ora_db_sid }} lvl0 2 high {{ rman_bkp_location }}/{{ ora_db_sid }}" }
