---
- name: Copy and Unarchive Oracle Home
  become: yes
  become_user: "{{ os_db_owner }}"
  unarchive:
    src: "{{ oracle_home_zip }}"
    dest: "{{ oracle_home }}/"

- name: Create sqlnet.ora / listener.ora / tnsnames.ora files
  template:
    src: "{{ item.source }}"
    dest: "{{ item.target }}"
    mode: '0775'
  with_items:
    - { source: "{{ role_path }}/templates/software/sqlnet.j2",   target: "{{ oracle_home }}/network/admin/sqlnet.ora" }
    - { source: "{{ role_path }}/templates/software/listener.j2", target: "{{ oracle_home }}/network/admin/listener.ora" }
    - { source: "{{ role_path }}/templates/software/tnsnames.j2", target: "{{ oracle_home }}/network/admin/tnsnames.ora" }

- name: Apply Workaround for runInstaller [WARNING] [INS-08101] on Linux 8 Platforms
  become: yes
  become_user: "{{ os_db_owner }}"
  lineinfile:
    path: "{{ oracle_home }}/cv/admin/cvu_config"
    line: "{{ item }}"
    state: present
    backup: yes
  with_items:
    - "# Manual fix to avoid runInstaller [WARNING] [INS-08101] on Linux 8 Platforms"
    - "CV_ASSUME_DISTID=OEL8"
  when: ansible_facts['distribution_major_version'] | int == 8

- name: Start runInstaller in SWO mode
  become: yes
  become_user: "{{ os_db_owner }}"
  shell: |
    {{ oracle_home }}/runInstaller  -ignorePrereqFailure -waitforcompletion -silent \
    -responseFile {{ oracle_home }}/install/response/db_install.rsp \
    oracle.install.option=INSTALL_DB_SWONLY \
    ORACLE_HOSTNAME={{ ansible_fqdn }} \
    UNIX_GROUP_NAME=oinstall \
    INVENTORY_LOCATION={{ oracle_inventory }} \
    SELECTED_LANGUAGES=en,en_GB \
    ORACLE_HOME={{ oracle_home }} \
    ORACLE_BASE={{ oracle_base }} \
    oracle.install.db.InstallEdition=EE \
    oracle.install.db.OSDBA_GROUP=dba \
    oracle.install.db.OSBACKUPDBA_GROUP=dba \
    oracle.install.db.OSDGDBA_GROUP=dba \
    oracle.install.db.OSKMDBA_GROUP=dba \
    oracle.install.db.OSRACDBA_GROUP=dba \
    SECURITY_UPDATES_VIA_MYORACLESUPPORT=false \
    DECLINE_SECURITY_UPDATES=true
  when: ora_version == 19
  ignore_errors: True

- name: Start runInstaller in SWO mode
  become: yes
  become_user: "{{ os_db_owner }}"
  shell: |
    {{ oracle_home }}/perl/bin/perl {{ oracle_home }}/clone/bin/clone.pl \
    ORACLE_BASE={{ oracle_base }} \
    ORACLE_HOME={{ oracle_home }} \
    INVENTORY_LOCATION={{ oracle_inventory }} \
    OSDBA_GROUP=dba \
    OSOPER_GROUP=dba \
    ORACLE_HOME_NAME="OH12102"
  when: ora_version == 12
  ignore_errors: True

- name: Execute oracle post-install scripts as root user
  shell: |
    {{ oracle_home }}/root.sh -silent
  ignore_errors: True

- name: Execute oracle post-install scripts as root user
  shell: |
    {{ oracle_inventory }}/orainstRoot.sh
  when: ora_version == 19
  ignore_errors: True
