---
- name: Create backup directory {{ bkp_dir }}/pg_dumpall
  become: yes
  become_user: "{{ os_pg_owner }}"
  file:
    path: "{{ bkp_dir }}/pg_dumpall"
    state: directory
    recurse: yes
    mode: '0700'

- name: Copy pg_dumpall.sh script
  become: yes
  become_user: "{{ os_pg_owner }}"
  template:
    src: "pg_dumpall.j2"
    dest: "/home/{{ os_pg_owner }}/dba/scripts/pg_dumpall.sh"
    mode: '0700'

- name: Schedule pg_dumpall.sh script in cron
  become: yes
  become_user: "{{ os_pg_owner }}"
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    weekday: "{{ item.weekday }}"
    job: "{{ item.job }}"
    state: present
  with_items:
    - { name: "Backup using pg_dumpall",
        minute: "10",
        hour: "00",
        weekday: "*",
        job: "/home/{{ os_pg_owner }}/dba/scripts/pg_dumpall.sh >> /home/{{ os_pg_owner }}/dba/logs/pg_dumpall.log 2>&1 &" }
