---
- name: Install non-PostgreSQL packages
  yum:
    name: "{{ pkg_name }}"
    state: present
  vars:
    pkg_name:
    - make
    - net-tools
    - sysstat
    - dos2unix
    - telnet
    - git

- name: Update /etc/hosts
  lineinfile:
    path: "/etc/hosts"
    line: "{{ ansible_default_ipv4.address }}     {{ ansible_fqdn }}     {{ ansible_hostname }}"
    state: present
    backup: yes

- name: Correct SELINUX
  selinux:
    policy: targeted
    state: permissive

- name: Stop and disable firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: False

- name: Create "postgres" OS group
  group:
    name: postgres
    state: present

- name: Create "{{ os_pg_owner }}" OS user
  user:
    name: "{{ os_pg_owner }}"
    password: "{{ os_pg_owner_pwd | password_hash('sha512', 'mysecretsalt') }}"
    group: postgres
    expires: -1

- name: Create additional directories and set permissions
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ os_pg_owner }}"
    group: postgres
    mode: '0775'
  with_items:
    - "{{ os_pg_data }}"
    - "{{ os_pg_logs }}"
    - "{{ os_pg_tablespaces }}"
    - "/home/{{ os_pg_owner }}/.ansible/tmp"

- name: Backup current sysctl.conf file
  copy:
    src: /etc/sysctl.conf
    dest: /etc/sysctl.conf_ansible_backup

- name: Linux kernel parameters tuning
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: kernel.sched_migration_cost_ns, value: 5000000}
    - { name: kernel.sched_autogroup_enabled, value: 0}
    - { name: kernel.randomize_va_space, value: 0}
    - { name: kernel.pid_max, value: 4194303}
    - { name: kernel.core_uses_pid, value: 1}
    - { name: kernel.numa_balancing, value: 0}
    - { name: vm.zone_reclaim_mode, value: 0}
    - { name: vm.dirty_background_bytes, value: 67108864}
    - { name: vm.dirty_bytes, value: 536870912}
    - { name: vm.dirty_expire_centisecs, value: 1000}
    - { name: vm.dirty_writeback_centisecs, value: 100}
    - { name: vm.overcommit_memory, value: 0} 
    - { name: vm.overcommit_ratio, value: 50}
    - { name: vm.min_free_kbytes, value: 102400}
    - { name: vm.swappiness, value: 1}
    - { name: net.core.netdev_max_backlog, value: 10000}
    - { name: net.core.somaxconn, value: 65535}
    - { name: net.ipv4.tcp_congestion_control, value: htcp}
    - { name: net.ipv4.tcp_rmem, value: 4096 87380 16777216}
    - { name: net.ipv4.tcp_wmem, value: 4096 65536 16777216}
    - { name: net.ipv4.tcp_max_tw_buckets, value: 720000}
    - { name: net.ipv4.tcp_fin_timeout, value: 30}
    - { name: net.core.netdev_budget, value: 900}
    - { name: net.ipv6.conf.all.disable_ipv6, value: 1}
    - { name: net.ipv6.conf.lo.disable_ipv6, value: 1}

- name: Enable Huge Pages
  sysctl:
    name: vm.nr_hugepages
    value: "{{ (((ansible_memtotal_mb * 0.5) / 2) + 10) | round | int | abs }}"
  when: ansible_memtotal_mb >= 12288
